version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "dev-feedback-service"
s3_bucket = "dev-aws-sam-cli-managed-samclisourcebucket"
s3_prefix = "dev-feedback-service"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"dev\" Environment=\"dev\""
image_repositories = []

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "prod-feedback-service"
s3_bucket = "prod-aws-sam-cli-managed-samclisourcebucket"
s3_prefix = "prod-feedback-service"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"prod\" Environment=\"prod\""
image_repositories = []
