AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Feedback-Service-Deployment-Descriptor

Parameters:
  Stage:
    Type: String
    Description: Stage name to deploy resources to
    AllowedValues:
      - dev
      - prod

Globals:
  Function:
    Runtime: java11
    MemorySize: 1024
    Timeout: 20
    AutoPublishAlias: !Ref Stage
    Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker
    CodeUri: ./application
    Tags:
      Stage: !Ref Stage
      Service: Feedback
      Resource: Lambda
    Environment:
      Variables:
        TABLE: !Ref FeedbackTable
        APPLICATION_ENVIRONMENT: !Ref Stage
        CLOUD_REGION: US_Standard
        MAIN_CLASS: com.tekcapsule.feedback.application.FeedbackApplication
        JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1

Resources:

  # Setup API Gateway

  FeedbackApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "feedback-${Stage}"
      StageName: !Ref Stage
      Cors:
        AllowMethods: "'POST, GET'"
        AllowHeaders: "'X-Forwarded-For, Content-Type, Authorization, X-User-Login, X-Channel-Code'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"
        AllowCredentials: false
      Variables:
        LAMBDA_ALIAS: !Ref Stage

  # Setup DynamoDB Table

  FeedbackTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Stage}Feedback"
      AttributeDefinitions:
        - AttributeName: emailId
          AttributeType: S
        - AttributeName: commentedOn
          AttributeType: S
      KeySchema:
        - AttributeName: emailId
          KeyType: HASH
        - AttributeName: commentedOn
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  # Setup Lambda Functions

  CreateFeedbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-Feedback-CreateFeedback"
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FeedbackTable
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: createFunction
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: feedback/create
            Method: post
            RestApiId:
              Ref: FeedbackApi

  MarkFeedbackAsReadFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-Feedback-MarkFeedbackAsRead"
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FeedbackTable
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: markAsReadFunction
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: feedback/markAsRead
            Method: post
            RestApiId:
              Ref: FeedbackApi

  GetAllFeedbacksFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-Feedback-GetAllFeedbacks"
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FeedbackTable
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: getAllFunction
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: feedback/getAll
            Method: post
            RestApiId:
              Ref: FeedbackApi

  # Set Output Variable

Outputs:
  ApiEndpoint:
    Description: "Feedback API endpoint."
    Value: !Sub "https://${FeedbackApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/feedback"